apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxysql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "proxysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: proxysql
        component: core
    spec:
      serviceAccountName: proxysql
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        {{- if .Values.agentSidecar.enabled }}
        - name: proxysql-agent
          image: "{{ .Values.agentSidecar.image.repository }}:{{ .Values.agentSidecar.image.tag }}"
          imagePullPolicy: {{ .Values.agentSidecar.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                # sleep for 5 minutes, so that the sidecar remains up long enough to kill proxysql
                # itself. Once proxysql is shutdown, this container issues an os.Exit(0) so it will
                # likely never actually be 5 minutes.
                command: ["/bin/sh", "-c", "echo 'sleeping for up to 300s while proxysql gracefully shuts down'; sleep 300"]
          command:
            - /app/proxysql-agent
            - --start_delay=5
            - --run_mode=core
            - --log.format=text
            - --log.level=DEBUG
          startupProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 250m
              memory: 250Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /var/lib/proxysql
              name: proxysql-var
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxysql-admin
              containerPort: 6032
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/proxysql
              name: proxysql-var
              readOnly: false
            - name: {{ .Release.Name }}-config
              mountPath: /etc/proxysql.cnf
              subPath: proxysql.cnf
            - name: {{ .Release.Name }}-config
              mountPath: /etc/mysql/conf.d/.my.cnf
              subPath: my.cnf
            - name: {{ .Release.Name }}-passwords
              mountPath: "/var/lib/proxysql/secrets"
              readOnly: true
          {{- if .Values.agentSidecar.enabled }}
          # all three probes are just pings for core pods, since we don't want to go unhealthy
          # if a backend vanishes for core pods.
          startupProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            runAsNonRoot: true
            runAsUser: 999
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - emptyDir: {}
          name: proxysql-var
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-cm
        - name: {{ .Release.Name }}-passwords
          secret:
            secretName: {{ .Release.Name }}-passwords
