{{- if not (lookup "v1" "ServiceAccount" "proxysql" "proxysql") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "proxysql.labels" . | indent 4 }}
  name: proxysql
  namespace: proxysql
{{- end }}
