{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if eq .Values.architecture "replication" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.tertiary.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: tertiary
  {{- if or .Values.tertiary.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.tertiary.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.tertiary.service.type }}
  {{- if and .Values.tertiary.service.clusterIP (eq .Values.tertiary.service.type "ClusterIP") }}
  clusterIP: {{ .Values.tertiary.service.clusterIP }}
  {{- end }}
  {{- if .Values.tertiary.service.sessionAffinity }}
  sessionAffinity: {{ .Values.tertiary.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.tertiary.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.tertiary.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.tertiary.service.type "LoadBalancer") (eq .Values.tertiary.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.tertiary.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.tertiary.service.type "LoadBalancer") (not (empty .Values.tertiary.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{- toYaml .Values.tertiary.service.loadBalancerSourceRanges | nindent 4}}
  {{- end }}
  {{- if and (eq .Values.tertiary.service.type "LoadBalancer") (not (empty .Values.tertiary.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.tertiary.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.tertiary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
      {{- if (and (or (eq .Values.tertiary.service.type "NodePort") (eq .Values.tertiary.service.type "LoadBalancer")) .Values.tertiary.service.nodePorts.mysql) }}
      nodePort: {{ .Values.tertiary.service.nodePorts.mysql }}
      {{- else if eq .Values.tertiary.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.tertiary.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.tertiary.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.tertiary.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: tertiary
{{- end }}
