replicaCount: 3

image:
  # pointing to the local (on my laptop) proxysql image tagged latest
  repository: proxysql
  tag: latest
  pullPolicy: Never
  ## to use the official images
  # repository: proxysql/proxysql
  # tag: 2.5.5-debian
  # pullPolicy: IfNotPresent

# proxysql-agent sidecar config
# FIXME: this is a separate repo
agentSidecar:
  enabled: true
  image:
    # points to the local (on my laptop) proxysql-agent image tagged latest
    repository: ghcr.io/persona-id/proxysql-agent
    tag: latest
    pullPolicy: Never

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 6033

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
