replicaCount: 3

image:
  ## to use to the locally built proxysql image
  # repository: persona-id/proxysql
  # tag: 1.1.0
  # pullPolicy: Never
  ## to use the official images
  repository: proxysql/proxysql
  tag: 3.0.2-debian
  pullPolicy: Always

# proxysql-agent sidecar config
agentSidecar:
  enabled: true
  image:
    # points to the local (on my laptop) persona-id/proxysql-agent
    # repository: persona-id/proxysql-agent
    # tag: 1.1.1
    # pullPolicy: Never
    ## to use official image
    repository: ghcr.io/persona-id/proxysql-agent
    tag: v1.1.2
    pullPolicy: Always

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 6032

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
