replicaCount: 3

image:
  # pointing to the local (on my laptop) proxysql image
  repository: persona-id/proxysql
  tag: 1.1.0
  pullPolicy: Never
  ## to use the official images
  # repository: proxysql/proxysql
  # tag: 2.5.5-debian
  # pullPolicy: Never

# proxysql-agent sidecar config
# FIXME: this is a separate repo
agentSidecar:
  enabled: true
  image:
    # points to the local (on my laptop) persona-id/proxysql-agent
    repository: persona-id/proxysql-agent
    tag: 1.1.0
    pullPolicy: Never

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 6032

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

