{{- $secret_name := "proxysql-satellite-passwords" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
data:
  # try to get the old secret
  # keep in mind, that a dry-run only returns an empty map
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  # check, if a secret is already set
  {{- if or (not $old_sec) (not $old_sec.data) }}
  # if not set, then generate a new password
  admin: {{ randAlphaNum 20 | b64enc }}
  radmin: {{ randAlphaNum 20 | b64enc }}
  cluster: {{ randAlphaNum 20 | b64enc }}
  monitor: {{ randAlphaNum 20 | b64enc }}
  mysql-backends: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # if set, then use the old value
  admin: {{ index $old_sec.data "admin" }}
  radmin: {{ index $old_sec.data "radmin" }}
  cluster: {{ index $old_sec.data "cluster" }}
  monitor: {{ index $old_sec.data "monitor" }}
  mysql-backends: {{ index $old_sec.data "mysql-backends" }}
  {{ end }}
